version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80" 

  backend:
    build:
      context: TTV-PROJECT
    ports:
      - "3000:3000" 
    depends_on:
      - frontend
